[package]
name = "speaker"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[[bin]]
name = "main"
path = "src/main.rs"

[[bin]]
name = "model"
path = "src/model.rs"

[[bin]]
name = "dbConfig"
path = "src/db_config.rs"

[dependencies]
mongodb-gridfs = "0.2.5"
record-audio = "0.1.1"
chrono = "0.4"
mongodb = "2.1"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
tokio = { version = "1.0", features = ["full"] }
lazy_static = "1.4.0"
futures = "0.3"
futures-util = "0.3.28"
rodio = "0.17.1"

[dependencies.pyo3]
version = "0.18.3"
features = ["auto-initialize"]